export const DUMMY_MENU_ITEMS = [
  {
    id: 1,
    title: "Tomato persimmon salad",
    desc: "Cherry tomato and fresh persimmon served on a bed of lettuce",
    price: 27,
    img: "https://lovesofresh.com/wp-content/uploads/2021/02/cali-bowl-1.png",
  },
  {
    id: 2,
    title: "Avocado panini extra filled",
    desc: "A warm, pressed panini filled with fresh cucumber and avocado",
    price: 24,
    img: "https://static.wixstatic.com/media/127d16_5639beaf16e0459c96a04e647dc46bb2~mv2.png/v1/crop/x_471,y_235,w_1247,h_1247/fill/w_560,h_560,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Fresh-Section-narrow.png",
  },
  {
    id: 3,
    title: "Peppercorn spaghetti leek",
    desc: "Spagetti topped with a blend of szechuan peppercorn and frizzled leek",
    price: 32,
    img: "https://d2ily9edavk8z4.cloudfront.net/uploads/products/buddha-bowl/Buddhabowl_new%20copy.png",
  },
  {
    id: 4,
    title: "Pepper and onion bell bagel",
    desc: "A warm bagel filled with bell pepper and dried onion",
    price: 18,
    img: "https://dietwithcare.com/wp-content/uploads/2019/10/banner_image_1.png",
  },
  {
    id: 5,
    title: "Pineapple and Barley soup extra",
    desc: "Fresh pineapple and barley combined into smooth soup",
    price: 26,
    img: "https://cdn.shopify.com/s/files/1/1980/2999/products/otrm_new_menu_salads_01_mykonos_2_1_1000x1000.png?v=1643914748",
  },
  {
    id: 6,
    title: "Cauliflower rambutan vindaloo",
    desc: "Spicy vindaloo made with fresh cauliflower and rambutan",
    price: 21,
    img: "https://www.maxpixel.net/static/photo/1x/Food-Salad-Vegetables-Fresh-Healthy-Healthy-Eating-4252467.png",
  },
  {
    id: 7,
    title: "Spaghetti squash salad extra",
    desc: "A crunchy salad featuring fresh cranberries and spaghetti squash",
    price: 27,
    img: "https://lovesofresh.com/wp-content/uploads/2020/12/Bitmap.png",
  },
  {
    id: 8,
    title: "Beetroot and onion stir fresh fry",
    desc: "Crunchy stir fry featuring fresh beetroot and dried onion",
    price: 25,
    img: "https://cdn.eatmightymeals.com/wp-content/uploads/2021/05/31190014/salmon-nicoise-salad.png",
  },
  {
    id: 9,
    title: "Apricot and pumpkin seed loaf",
    desc: "Crunchy bread made with dried apricots and pumpkin seeds",
    price: 34,
    img: "https://getfresh.co.th/wp-content/uploads/2022/02/Layer-1.png",
  },
  {
    id: 10,
    title: "breakfast cereal & Pumpkin",
    desc: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "https://justfresh.com/wp-content/uploads/2021/09/RedWhiteBlueSalad_Alpha.png",
  },
];
